server:
  port: 8088

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation?serverTimezone=GMT%2B8
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.qq.com
    username: vgbhfive@foxmail.com
    password: 
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
  mvc:
    favicon:
      enabled: false
  swagger:
    enabled: true
    base-package: cn.vgbhfive.graduationproject
